// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/protobuf/CustomMessageProtocol.proto

package com.elisland.customprotocol;

public final class CustomMessageData {
  private CustomMessageData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.elisland.customprotocol.MessageData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 length = 1;</code>
     */
    boolean hasLength();
    /**
     * <code>required int64 length = 1;</code>
     */
    long getLength();

    /**
     * <code>optional .com.elisland.customprotocol.MessageData.Content content = 2;</code>
     */
    boolean hasContent();
    /**
     * <code>optional .com.elisland.customprotocol.MessageData.Content content = 2;</code>
     */
    com.elisland.customprotocol.CustomMessageData.MessageData.Content getContent();
    /**
     * <code>optional .com.elisland.customprotocol.MessageData.Content content = 2;</code>
     */
    com.elisland.customprotocol.CustomMessageData.MessageData.ContentOrBuilder getContentOrBuilder();

    /**
     * <code>optional .com.elisland.customprotocol.MessageData.DataType order = 3;</code>
     */
    boolean hasOrder();
    /**
     * <code>optional .com.elisland.customprotocol.MessageData.DataType order = 3;</code>
     */
    com.elisland.customprotocol.CustomMessageData.MessageData.DataType getOrder();
  }
  /**
   * Protobuf type {@code com.elisland.customprotocol.MessageData}
   */
  public  static final class MessageData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.elisland.customprotocol.MessageData)
      MessageDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MessageData.newBuilder() to construct.
    private MessageData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessageData() {
      order_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MessageData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              length_ = input.readInt64();
              break;
            }
            case 18: {
              com.elisland.customprotocol.CustomMessageData.MessageData.Content.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) != 0)) {
                subBuilder = content_.toBuilder();
              }
              content_ = input.readMessage(com.elisland.customprotocol.CustomMessageData.MessageData.Content.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(content_);
                content_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              com.elisland.customprotocol.CustomMessageData.MessageData.DataType value = com.elisland.customprotocol.CustomMessageData.MessageData.DataType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                order_ = rawValue;
              }
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.elisland.customprotocol.CustomMessageData.internal_static_com_elisland_customprotocol_MessageData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.elisland.customprotocol.CustomMessageData.internal_static_com_elisland_customprotocol_MessageData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.elisland.customprotocol.CustomMessageData.MessageData.class, com.elisland.customprotocol.CustomMessageData.MessageData.Builder.class);
    }

    /**
     * Protobuf enum {@code com.elisland.customprotocol.MessageData.DataType}
     */
    public enum DataType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       *上线登录验证环节 等基础信息上报
       * </pre>
       *
       * <code>REQ_LOGIN = 0;</code>
       */
      REQ_LOGIN(0),
      /**
       * <pre>
       *返回上线登录状态与基础信息
       * </pre>
       *
       * <code>RSP_LOGIN = 1;</code>
       */
      RSP_LOGIN(1),
      /**
       * <pre>
       *心跳
       * </pre>
       *
       * <code>PING = 2;</code>
       */
      PING(2),
      /**
       * <pre>
       *心跳
       * </pre>
       *
       * <code>PONG = 3;</code>
       */
      PONG(3),
      /**
       * <pre>
       *动作请求
       * </pre>
       *
       * <code>REQ_ACT = 4;</code>
       */
      REQ_ACT(4),
      /**
       * <pre>
       *动作响应
       * </pre>
       *
       * <code>RSP_ACT = 5;</code>
       */
      RSP_ACT(5),
      /**
       * <pre>
       *指令请求
       * </pre>
       *
       * <code>REQ_CMD = 6;</code>
       */
      REQ_CMD(6),
      /**
       * <pre>
       *指令响应
       * </pre>
       *
       * <code>RSP_CMD = 7;</code>
       */
      RSP_CMD(7),
      /**
       * <pre>
       *日志请求
       * </pre>
       *
       * <code>REQ_LOG = 8;</code>
       */
      REQ_LOG(8),
      /**
       * <pre>
       *日志响应
       * </pre>
       *
       * <code>RSP_LOG = 9;</code>
       */
      RSP_LOG(9),
      ;

      /**
       * <pre>
       *上线登录验证环节 等基础信息上报
       * </pre>
       *
       * <code>REQ_LOGIN = 0;</code>
       */
      public static final int REQ_LOGIN_VALUE = 0;
      /**
       * <pre>
       *返回上线登录状态与基础信息
       * </pre>
       *
       * <code>RSP_LOGIN = 1;</code>
       */
      public static final int RSP_LOGIN_VALUE = 1;
      /**
       * <pre>
       *心跳
       * </pre>
       *
       * <code>PING = 2;</code>
       */
      public static final int PING_VALUE = 2;
      /**
       * <pre>
       *心跳
       * </pre>
       *
       * <code>PONG = 3;</code>
       */
      public static final int PONG_VALUE = 3;
      /**
       * <pre>
       *动作请求
       * </pre>
       *
       * <code>REQ_ACT = 4;</code>
       */
      public static final int REQ_ACT_VALUE = 4;
      /**
       * <pre>
       *动作响应
       * </pre>
       *
       * <code>RSP_ACT = 5;</code>
       */
      public static final int RSP_ACT_VALUE = 5;
      /**
       * <pre>
       *指令请求
       * </pre>
       *
       * <code>REQ_CMD = 6;</code>
       */
      public static final int REQ_CMD_VALUE = 6;
      /**
       * <pre>
       *指令响应
       * </pre>
       *
       * <code>RSP_CMD = 7;</code>
       */
      public static final int RSP_CMD_VALUE = 7;
      /**
       * <pre>
       *日志请求
       * </pre>
       *
       * <code>REQ_LOG = 8;</code>
       */
      public static final int REQ_LOG_VALUE = 8;
      /**
       * <pre>
       *日志响应
       * </pre>
       *
       * <code>RSP_LOG = 9;</code>
       */
      public static final int RSP_LOG_VALUE = 9;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataType valueOf(int value) {
        return forNumber(value);
      }

      public static DataType forNumber(int value) {
        switch (value) {
          case 0: return REQ_LOGIN;
          case 1: return RSP_LOGIN;
          case 2: return PING;
          case 3: return PONG;
          case 4: return REQ_ACT;
          case 5: return RSP_ACT;
          case 6: return REQ_CMD;
          case 7: return RSP_CMD;
          case 8: return REQ_LOG;
          case 9: return RSP_LOG;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DataType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          DataType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
              public DataType findValueByNumber(int number) {
                return DataType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.elisland.customprotocol.CustomMessageData.MessageData.getDescriptor().getEnumTypes().get(0);
      }

      private static final DataType[] VALUES = values();

      public static DataType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private DataType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.elisland.customprotocol.MessageData.DataType)
    }

    public interface ContentOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.elisland.customprotocol.MessageData.Content)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional int64 contentLength = 1;</code>
       */
      boolean hasContentLength();
      /**
       * <code>optional int64 contentLength = 1;</code>
       */
      long getContentLength();

      /**
       * <code>optional string data = 2;</code>
       */
      boolean hasData();
      /**
       * <code>optional string data = 2;</code>
       */
      java.lang.String getData();
      /**
       * <code>optional string data = 2;</code>
       */
      com.google.protobuf.ByteString
          getDataBytes();
    }
    /**
     * Protobuf type {@code com.elisland.customprotocol.MessageData.Content}
     */
    public  static final class Content extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.elisland.customprotocol.MessageData.Content)
        ContentOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Content.newBuilder() to construct.
      private Content(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Content() {
        data_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Content(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                bitField0_ |= 0x00000001;
                contentLength_ = input.readInt64();
                break;
              }
              case 18: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000002;
                data_ = bs;
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.elisland.customprotocol.CustomMessageData.internal_static_com_elisland_customprotocol_MessageData_Content_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.elisland.customprotocol.CustomMessageData.internal_static_com_elisland_customprotocol_MessageData_Content_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.elisland.customprotocol.CustomMessageData.MessageData.Content.class, com.elisland.customprotocol.CustomMessageData.MessageData.Content.Builder.class);
      }

      private int bitField0_;
      public static final int CONTENTLENGTH_FIELD_NUMBER = 1;
      private long contentLength_;
      /**
       * <code>optional int64 contentLength = 1;</code>
       */
      public boolean hasContentLength() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional int64 contentLength = 1;</code>
       */
      public long getContentLength() {
        return contentLength_;
      }

      public static final int DATA_FIELD_NUMBER = 2;
      private volatile java.lang.Object data_;
      /**
       * <code>optional string data = 2;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string data = 2;</code>
       */
      public java.lang.String getData() {
        java.lang.Object ref = data_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            data_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string data = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) != 0)) {
          output.writeInt64(1, contentLength_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, data_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) != 0)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(1, contentLength_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, data_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.elisland.customprotocol.CustomMessageData.MessageData.Content)) {
          return super.equals(obj);
        }
        com.elisland.customprotocol.CustomMessageData.MessageData.Content other = (com.elisland.customprotocol.CustomMessageData.MessageData.Content) obj;

        if (hasContentLength() != other.hasContentLength()) return false;
        if (hasContentLength()) {
          if (getContentLength()
              != other.getContentLength()) return false;
        }
        if (hasData() != other.hasData()) return false;
        if (hasData()) {
          if (!getData()
              .equals(other.getData())) return false;
        }
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasContentLength()) {
          hash = (37 * hash) + CONTENTLENGTH_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getContentLength());
        }
        if (hasData()) {
          hash = (37 * hash) + DATA_FIELD_NUMBER;
          hash = (53 * hash) + getData().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.elisland.customprotocol.CustomMessageData.MessageData.Content parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.elisland.customprotocol.CustomMessageData.MessageData.Content parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.elisland.customprotocol.CustomMessageData.MessageData.Content parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.elisland.customprotocol.CustomMessageData.MessageData.Content parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.elisland.customprotocol.CustomMessageData.MessageData.Content parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.elisland.customprotocol.CustomMessageData.MessageData.Content parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.elisland.customprotocol.CustomMessageData.MessageData.Content parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.elisland.customprotocol.CustomMessageData.MessageData.Content parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.elisland.customprotocol.CustomMessageData.MessageData.Content parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.elisland.customprotocol.CustomMessageData.MessageData.Content parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.elisland.customprotocol.CustomMessageData.MessageData.Content parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.elisland.customprotocol.CustomMessageData.MessageData.Content parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.elisland.customprotocol.CustomMessageData.MessageData.Content prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.elisland.customprotocol.MessageData.Content}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.elisland.customprotocol.MessageData.Content)
          com.elisland.customprotocol.CustomMessageData.MessageData.ContentOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.elisland.customprotocol.CustomMessageData.internal_static_com_elisland_customprotocol_MessageData_Content_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.elisland.customprotocol.CustomMessageData.internal_static_com_elisland_customprotocol_MessageData_Content_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.elisland.customprotocol.CustomMessageData.MessageData.Content.class, com.elisland.customprotocol.CustomMessageData.MessageData.Content.Builder.class);
        }

        // Construct using com.elisland.customprotocol.CustomMessageData.MessageData.Content.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          contentLength_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000001);
          data_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.elisland.customprotocol.CustomMessageData.internal_static_com_elisland_customprotocol_MessageData_Content_descriptor;
        }

        @java.lang.Override
        public com.elisland.customprotocol.CustomMessageData.MessageData.Content getDefaultInstanceForType() {
          return com.elisland.customprotocol.CustomMessageData.MessageData.Content.getDefaultInstance();
        }

        @java.lang.Override
        public com.elisland.customprotocol.CustomMessageData.MessageData.Content build() {
          com.elisland.customprotocol.CustomMessageData.MessageData.Content result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public com.elisland.customprotocol.CustomMessageData.MessageData.Content buildPartial() {
          com.elisland.customprotocol.CustomMessageData.MessageData.Content result = new com.elisland.customprotocol.CustomMessageData.MessageData.Content(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            result.contentLength_ = contentLength_;
            to_bitField0_ |= 0x00000001;
          }
          if (((from_bitField0_ & 0x00000002) != 0)) {
            to_bitField0_ |= 0x00000002;
          }
          result.data_ = data_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.elisland.customprotocol.CustomMessageData.MessageData.Content) {
            return mergeFrom((com.elisland.customprotocol.CustomMessageData.MessageData.Content)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.elisland.customprotocol.CustomMessageData.MessageData.Content other) {
          if (other == com.elisland.customprotocol.CustomMessageData.MessageData.Content.getDefaultInstance()) return this;
          if (other.hasContentLength()) {
            setContentLength(other.getContentLength());
          }
          if (other.hasData()) {
            bitField0_ |= 0x00000002;
            data_ = other.data_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.elisland.customprotocol.CustomMessageData.MessageData.Content parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.elisland.customprotocol.CustomMessageData.MessageData.Content) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private long contentLength_ ;
        /**
         * <code>optional int64 contentLength = 1;</code>
         */
        public boolean hasContentLength() {
          return ((bitField0_ & 0x00000001) != 0);
        }
        /**
         * <code>optional int64 contentLength = 1;</code>
         */
        public long getContentLength() {
          return contentLength_;
        }
        /**
         * <code>optional int64 contentLength = 1;</code>
         */
        public Builder setContentLength(long value) {
          bitField0_ |= 0x00000001;
          contentLength_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int64 contentLength = 1;</code>
         */
        public Builder clearContentLength() {
          bitField0_ = (bitField0_ & ~0x00000001);
          contentLength_ = 0L;
          onChanged();
          return this;
        }

        private java.lang.Object data_ = "";
        /**
         * <code>optional string data = 2;</code>
         */
        public boolean hasData() {
          return ((bitField0_ & 0x00000002) != 0);
        }
        /**
         * <code>optional string data = 2;</code>
         */
        public java.lang.String getData() {
          java.lang.Object ref = data_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              data_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string data = 2;</code>
         */
        public com.google.protobuf.ByteString
            getDataBytes() {
          java.lang.Object ref = data_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            data_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string data = 2;</code>
         */
        public Builder setData(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          data_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string data = 2;</code>
         */
        public Builder clearData() {
          bitField0_ = (bitField0_ & ~0x00000002);
          data_ = getDefaultInstance().getData();
          onChanged();
          return this;
        }
        /**
         * <code>optional string data = 2;</code>
         */
        public Builder setDataBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          data_ = value;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:com.elisland.customprotocol.MessageData.Content)
      }

      // @@protoc_insertion_point(class_scope:com.elisland.customprotocol.MessageData.Content)
      private static final com.elisland.customprotocol.CustomMessageData.MessageData.Content DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.elisland.customprotocol.CustomMessageData.MessageData.Content();
      }

      public static com.elisland.customprotocol.CustomMessageData.MessageData.Content getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<Content>
          PARSER = new com.google.protobuf.AbstractParser<Content>() {
        @java.lang.Override
        public Content parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Content(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Content> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Content> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public com.elisland.customprotocol.CustomMessageData.MessageData.Content getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int LENGTH_FIELD_NUMBER = 1;
    private long length_;
    /**
     * <code>required int64 length = 1;</code>
     */
    public boolean hasLength() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int64 length = 1;</code>
     */
    public long getLength() {
      return length_;
    }

    public static final int CONTENT_FIELD_NUMBER = 2;
    private com.elisland.customprotocol.CustomMessageData.MessageData.Content content_;
    /**
     * <code>optional .com.elisland.customprotocol.MessageData.Content content = 2;</code>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .com.elisland.customprotocol.MessageData.Content content = 2;</code>
     */
    public com.elisland.customprotocol.CustomMessageData.MessageData.Content getContent() {
      return content_ == null ? com.elisland.customprotocol.CustomMessageData.MessageData.Content.getDefaultInstance() : content_;
    }
    /**
     * <code>optional .com.elisland.customprotocol.MessageData.Content content = 2;</code>
     */
    public com.elisland.customprotocol.CustomMessageData.MessageData.ContentOrBuilder getContentOrBuilder() {
      return content_ == null ? com.elisland.customprotocol.CustomMessageData.MessageData.Content.getDefaultInstance() : content_;
    }

    public static final int ORDER_FIELD_NUMBER = 3;
    private int order_;
    /**
     * <code>optional .com.elisland.customprotocol.MessageData.DataType order = 3;</code>
     */
    public boolean hasOrder() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .com.elisland.customprotocol.MessageData.DataType order = 3;</code>
     */
    public com.elisland.customprotocol.CustomMessageData.MessageData.DataType getOrder() {
      @SuppressWarnings("deprecation")
      com.elisland.customprotocol.CustomMessageData.MessageData.DataType result = com.elisland.customprotocol.CustomMessageData.MessageData.DataType.valueOf(order_);
      return result == null ? com.elisland.customprotocol.CustomMessageData.MessageData.DataType.REQ_LOGIN : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasLength()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(1, length_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(2, getContent());
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeEnum(3, order_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, length_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getContent());
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, order_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.elisland.customprotocol.CustomMessageData.MessageData)) {
        return super.equals(obj);
      }
      com.elisland.customprotocol.CustomMessageData.MessageData other = (com.elisland.customprotocol.CustomMessageData.MessageData) obj;

      if (hasLength() != other.hasLength()) return false;
      if (hasLength()) {
        if (getLength()
            != other.getLength()) return false;
      }
      if (hasContent() != other.hasContent()) return false;
      if (hasContent()) {
        if (!getContent()
            .equals(other.getContent())) return false;
      }
      if (hasOrder() != other.hasOrder()) return false;
      if (hasOrder()) {
        if (order_ != other.order_) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasLength()) {
        hash = (37 * hash) + LENGTH_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getLength());
      }
      if (hasContent()) {
        hash = (37 * hash) + CONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getContent().hashCode();
      }
      if (hasOrder()) {
        hash = (37 * hash) + ORDER_FIELD_NUMBER;
        hash = (53 * hash) + order_;
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.elisland.customprotocol.CustomMessageData.MessageData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.elisland.customprotocol.CustomMessageData.MessageData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.elisland.customprotocol.CustomMessageData.MessageData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.elisland.customprotocol.CustomMessageData.MessageData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.elisland.customprotocol.CustomMessageData.MessageData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.elisland.customprotocol.CustomMessageData.MessageData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.elisland.customprotocol.CustomMessageData.MessageData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.elisland.customprotocol.CustomMessageData.MessageData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.elisland.customprotocol.CustomMessageData.MessageData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.elisland.customprotocol.CustomMessageData.MessageData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.elisland.customprotocol.CustomMessageData.MessageData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.elisland.customprotocol.CustomMessageData.MessageData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.elisland.customprotocol.CustomMessageData.MessageData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.elisland.customprotocol.MessageData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.elisland.customprotocol.MessageData)
        com.elisland.customprotocol.CustomMessageData.MessageDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.elisland.customprotocol.CustomMessageData.internal_static_com_elisland_customprotocol_MessageData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.elisland.customprotocol.CustomMessageData.internal_static_com_elisland_customprotocol_MessageData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.elisland.customprotocol.CustomMessageData.MessageData.class, com.elisland.customprotocol.CustomMessageData.MessageData.Builder.class);
      }

      // Construct using com.elisland.customprotocol.CustomMessageData.MessageData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getContentFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        length_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (contentBuilder_ == null) {
          content_ = null;
        } else {
          contentBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        order_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.elisland.customprotocol.CustomMessageData.internal_static_com_elisland_customprotocol_MessageData_descriptor;
      }

      @java.lang.Override
      public com.elisland.customprotocol.CustomMessageData.MessageData getDefaultInstanceForType() {
        return com.elisland.customprotocol.CustomMessageData.MessageData.getDefaultInstance();
      }

      @java.lang.Override
      public com.elisland.customprotocol.CustomMessageData.MessageData build() {
        com.elisland.customprotocol.CustomMessageData.MessageData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.elisland.customprotocol.CustomMessageData.MessageData buildPartial() {
        com.elisland.customprotocol.CustomMessageData.MessageData result = new com.elisland.customprotocol.CustomMessageData.MessageData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.length_ = length_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          if (contentBuilder_ == null) {
            result.content_ = content_;
          } else {
            result.content_ = contentBuilder_.build();
          }
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.order_ = order_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.elisland.customprotocol.CustomMessageData.MessageData) {
          return mergeFrom((com.elisland.customprotocol.CustomMessageData.MessageData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.elisland.customprotocol.CustomMessageData.MessageData other) {
        if (other == com.elisland.customprotocol.CustomMessageData.MessageData.getDefaultInstance()) return this;
        if (other.hasLength()) {
          setLength(other.getLength());
        }
        if (other.hasContent()) {
          mergeContent(other.getContent());
        }
        if (other.hasOrder()) {
          setOrder(other.getOrder());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasLength()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.elisland.customprotocol.CustomMessageData.MessageData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.elisland.customprotocol.CustomMessageData.MessageData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long length_ ;
      /**
       * <code>required int64 length = 1;</code>
       */
      public boolean hasLength() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int64 length = 1;</code>
       */
      public long getLength() {
        return length_;
      }
      /**
       * <code>required int64 length = 1;</code>
       */
      public Builder setLength(long value) {
        bitField0_ |= 0x00000001;
        length_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 length = 1;</code>
       */
      public Builder clearLength() {
        bitField0_ = (bitField0_ & ~0x00000001);
        length_ = 0L;
        onChanged();
        return this;
      }

      private com.elisland.customprotocol.CustomMessageData.MessageData.Content content_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.elisland.customprotocol.CustomMessageData.MessageData.Content, com.elisland.customprotocol.CustomMessageData.MessageData.Content.Builder, com.elisland.customprotocol.CustomMessageData.MessageData.ContentOrBuilder> contentBuilder_;
      /**
       * <code>optional .com.elisland.customprotocol.MessageData.Content content = 2;</code>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional .com.elisland.customprotocol.MessageData.Content content = 2;</code>
       */
      public com.elisland.customprotocol.CustomMessageData.MessageData.Content getContent() {
        if (contentBuilder_ == null) {
          return content_ == null ? com.elisland.customprotocol.CustomMessageData.MessageData.Content.getDefaultInstance() : content_;
        } else {
          return contentBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.elisland.customprotocol.MessageData.Content content = 2;</code>
       */
      public Builder setContent(com.elisland.customprotocol.CustomMessageData.MessageData.Content value) {
        if (contentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          content_ = value;
          onChanged();
        } else {
          contentBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.elisland.customprotocol.MessageData.Content content = 2;</code>
       */
      public Builder setContent(
          com.elisland.customprotocol.CustomMessageData.MessageData.Content.Builder builderForValue) {
        if (contentBuilder_ == null) {
          content_ = builderForValue.build();
          onChanged();
        } else {
          contentBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.elisland.customprotocol.MessageData.Content content = 2;</code>
       */
      public Builder mergeContent(com.elisland.customprotocol.CustomMessageData.MessageData.Content value) {
        if (contentBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
              content_ != null &&
              content_ != com.elisland.customprotocol.CustomMessageData.MessageData.Content.getDefaultInstance()) {
            content_ =
              com.elisland.customprotocol.CustomMessageData.MessageData.Content.newBuilder(content_).mergeFrom(value).buildPartial();
          } else {
            content_ = value;
          }
          onChanged();
        } else {
          contentBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.elisland.customprotocol.MessageData.Content content = 2;</code>
       */
      public Builder clearContent() {
        if (contentBuilder_ == null) {
          content_ = null;
          onChanged();
        } else {
          contentBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .com.elisland.customprotocol.MessageData.Content content = 2;</code>
       */
      public com.elisland.customprotocol.CustomMessageData.MessageData.Content.Builder getContentBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getContentFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.elisland.customprotocol.MessageData.Content content = 2;</code>
       */
      public com.elisland.customprotocol.CustomMessageData.MessageData.ContentOrBuilder getContentOrBuilder() {
        if (contentBuilder_ != null) {
          return contentBuilder_.getMessageOrBuilder();
        } else {
          return content_ == null ?
              com.elisland.customprotocol.CustomMessageData.MessageData.Content.getDefaultInstance() : content_;
        }
      }
      /**
       * <code>optional .com.elisland.customprotocol.MessageData.Content content = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.elisland.customprotocol.CustomMessageData.MessageData.Content, com.elisland.customprotocol.CustomMessageData.MessageData.Content.Builder, com.elisland.customprotocol.CustomMessageData.MessageData.ContentOrBuilder> 
          getContentFieldBuilder() {
        if (contentBuilder_ == null) {
          contentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.elisland.customprotocol.CustomMessageData.MessageData.Content, com.elisland.customprotocol.CustomMessageData.MessageData.Content.Builder, com.elisland.customprotocol.CustomMessageData.MessageData.ContentOrBuilder>(
                  getContent(),
                  getParentForChildren(),
                  isClean());
          content_ = null;
        }
        return contentBuilder_;
      }

      private int order_ = 0;
      /**
       * <code>optional .com.elisland.customprotocol.MessageData.DataType order = 3;</code>
       */
      public boolean hasOrder() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional .com.elisland.customprotocol.MessageData.DataType order = 3;</code>
       */
      public com.elisland.customprotocol.CustomMessageData.MessageData.DataType getOrder() {
        @SuppressWarnings("deprecation")
        com.elisland.customprotocol.CustomMessageData.MessageData.DataType result = com.elisland.customprotocol.CustomMessageData.MessageData.DataType.valueOf(order_);
        return result == null ? com.elisland.customprotocol.CustomMessageData.MessageData.DataType.REQ_LOGIN : result;
      }
      /**
       * <code>optional .com.elisland.customprotocol.MessageData.DataType order = 3;</code>
       */
      public Builder setOrder(com.elisland.customprotocol.CustomMessageData.MessageData.DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        order_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.elisland.customprotocol.MessageData.DataType order = 3;</code>
       */
      public Builder clearOrder() {
        bitField0_ = (bitField0_ & ~0x00000004);
        order_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.elisland.customprotocol.MessageData)
    }

    // @@protoc_insertion_point(class_scope:com.elisland.customprotocol.MessageData)
    private static final com.elisland.customprotocol.CustomMessageData.MessageData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.elisland.customprotocol.CustomMessageData.MessageData();
    }

    public static com.elisland.customprotocol.CustomMessageData.MessageData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<MessageData>
        PARSER = new com.google.protobuf.AbstractParser<MessageData>() {
      @java.lang.Override
      public MessageData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessageData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MessageData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MessageData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.elisland.customprotocol.CustomMessageData.MessageData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_elisland_customprotocol_MessageData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_elisland_customprotocol_MessageData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_elisland_customprotocol_MessageData_Content_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_elisland_customprotocol_MessageData_Content_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(src/protobuf/CustomMessageProtocol.pro" +
      "to\022\033com.elisland.customprotocol\"\337\002\n\013Mess" +
      "ageData\022\016\n\006length\030\001 \002(\003\022A\n\007content\030\002 \001(\013" +
      "20.com.elisland.customprotocol.MessageDa" +
      "ta.Content\022@\n\005order\030\003 \001(\01621.com.elisland" +
      ".customprotocol.MessageData.DataType\032.\n\007" +
      "Content\022\025\n\rcontentLength\030\001 \001(\003\022\014\n\004data\030\002" +
      " \001(\t\"\212\001\n\010DataType\022\r\n\tREQ_LOGIN\020\000\022\r\n\tRSP_" +
      "LOGIN\020\001\022\010\n\004PING\020\002\022\010\n\004PONG\020\003\022\013\n\007REQ_ACT\020\004" +
      "\022\013\n\007RSP_ACT\020\005\022\013\n\007REQ_CMD\020\006\022\013\n\007RSP_CMD\020\007\022" +
      "\013\n\007REQ_LOG\020\010\022\013\n\007RSP_LOG\020\tB2\n\033com.elislan" +
      "d.customprotocolB\021CustomMessageDataH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_elisland_customprotocol_MessageData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_elisland_customprotocol_MessageData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_elisland_customprotocol_MessageData_descriptor,
        new java.lang.String[] { "Length", "Content", "Order", });
    internal_static_com_elisland_customprotocol_MessageData_Content_descriptor =
      internal_static_com_elisland_customprotocol_MessageData_descriptor.getNestedTypes().get(0);
    internal_static_com_elisland_customprotocol_MessageData_Content_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_elisland_customprotocol_MessageData_Content_descriptor,
        new java.lang.String[] { "ContentLength", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
